"""add brand column and barcode_cache table

Revision ID: 0ace9f1e8ae1
Revises: 167ab54fe2d2
Create Date: 2026-03-10 10:46:44.463470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ace9f1e8ae1'
down_revision: Union[str, None] = '167ab54fe2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_cache',
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.add_column('food_items', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'brand')
    op.drop_table('barcode_cache')
    # ### end Alembic commands ###
