"""add category shelf_life photo_path and shopping_items table

Revision ID: 202b1cbca197
Revises: 0ace9f1e8ae1
Create Date: 2026-03-10 11:19:02.934142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202b1cbca197'
down_revision: Union[str, None] = '0ace9f1e8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_item_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('food_items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('food_items', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('food_items', sa.Column('photo_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_column('food_items', 'photo_path')
    op.drop_column('food_items', 'shelf_life_days')
    op.drop_column('food_items', 'category')
    op.drop_table('shopping_items')
    # ### end Alembic commands ###
