"""add freezers table and freezer_id column

Revision ID: a7f65f4de5b9
Revises: 202b1cbca197
Create Date: 2026-03-10 11:34:52.497933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f65f4de5b9'
down_revision: Union[str, None] = '202b1cbca197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freezers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('food_items', sa.Column('freezer_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'food_items', 'freezers', ['freezer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.drop_column('food_items', 'freezer_id')
    op.drop_table('freezers')
    # ### end Alembic commands ###
